site:
  name: Mi Sitio Web
  description: Un sitio web incre√≠ble
  author: Tu Nombre
  
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

